version: '3.7'

services:
  agent:
    image: portainer/agent:${AGENT_IMAGE_TAG:-latest}
    environment:
      - LOG_LEVEL
      - AGENT_PORT
      - AGENT_CLUSTER_ADDR=tasks.{{.Service.Name}}
    networks:
      - portainer-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${AGENT_DOCKER_VOLUMES_PATH:-/var/lib/docker/volumes}:/var/lib/docker/volumes
    deploy:
      mode: global
      restart_policy:
        delay: ${AGENT_RESTART_POLICY_DELAY:-3s}
        window: ${AGENT_RESTART_POLICY_WINDOW:-30s}
      resources:
        limits:
          cpus: "${AGENT_LIMITS_CPUS:-1}"
          memory: ${AGENT_LIMITS_MEMORY:-32M}
        reservations:
          memory: ${AGENT_RESERVATIONS_MEMORY:-16M}

  portainer:
    image: portainer/portainer:${PORTAINER_IMAGE_TAG:-latest}
    command: -H tcp://tasks.${STACK_NAME:-portainer}_agent:${AGENT_PORT} --tlsskipverify
    networks:
      - portainer-net
      - traefik-net
    volumes:
      - portainer-vol:/data
    deploy:
      mode: replicated
      replicas: ${PORTAINER_REPLICAS:-1}
      labels:
        traefik.frontend.rule: Host:${PORTAINER_SUBDOMAIN}.${PUBLIC_HOSTNAME}
        traefik.backend: portainer
        traefik.port: '9000'
      restart_policy:
        delay: ${PORTAINER_RESTART_POLICY_DELAY:-10s}
        window: ${PORTAINER_RESTART_POLICY_WINDOW:-1m}
      placement:
        constraints:
          - ${PORTAINER_PLACEMENT_CONSTRAINT:-node.hostname == node}
      resources:
        limits:
          cpus: "${PORTAINER_LIMITS_CPUS:-2}"
          memory: ${PORTAINER_LIMITS_MEMORY:-64M}
        reservations:
          memory: ${PORTAINER_RESERVATIONS_MEMORY:-32M}

networks:
  portainer-net:
    name: ${PORTAINER_NET_NAME:-portainer-net}
    driver: overlay
    attachable: ${PORTAINER_NET_ATTACHABLE:-true}

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true

volumes:
  portainer-vol:
    name: ${PORTAINER_VOL_NAME:-portainer-vol}
